server:
  port: 8085
spring:
  datasource:
    url: "jdbc:mysql://127.0.0.1:3306/spring2.0"
    username: root
    password: root
  #  h2:
  #    console:
  #      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true